// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace ZodiacGameplayTags
{
	ZODIAC_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	ZODIAC_API	FGameplayTag GetCooldownExtendedTag(const FGameplayTag& SkillTag);

	// Heroes
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Name_Twinblast);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Name_Murdock);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Slot_Slot1);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Slot_Slot2);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Changed_HealthBar_Message);

	// Declare all of the custom native tags that Zodiac will use
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Stack);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Attribute);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stack);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Jump);
	
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Slot_Primary);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Slot_Secondary);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Slot_Ultimate);

	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Cost_None);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Cost_Bullet);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Cost_Cooldown);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Cost_Gauge);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Skill_Cost_Ultimate);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeroChanged_PrimarySkill_Message);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeroChanged_SecondarySkill_Message);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeroChanged_UltimateSkill_Message);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Sprint);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Damaged_Message);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_SkillMultiplier);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_UltimateGauge);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Ultimate_Cost);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);

	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Escape);

	// Gameplay Message channels
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_HeroChanged_SkillSlot);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_HeroChanged);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_SkillDuration);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_SkillCommit);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_SkillSlot_TagStackChanged);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_SkillSlot_Created);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_AttributeChanged_Ultimate);

	// Tags for GameplayCue
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Rifle_Fire);

	// Hero Ability Cooldown
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cooldown);
	
	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	ZODIAC_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	ZODIAC_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
};
