// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace ZodiacGameplayTags
{
	ZODIAC_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	ZODIAC_API	FGameplayTag GetCooldownExtendedTag(const FGameplayTag& SkillTag);

	// Declare all of the custom native tags that Zodiac will use
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Stack);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Stack_MagazineAmmo);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Stack_MagazineSize);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cost_Attribute);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Jump);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Sprint);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Fly);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damaged_Message);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JustLanded);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JustLifted);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Elimination);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Traversal);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Reset);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_RequestReset);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageMultiplier);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Duration);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Amount);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Cost);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Cooldown);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Ultimate);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_InfiniteAmmo);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Walking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Running);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Traversal);
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Attacking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Disabled);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weapon_Firing);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_WeaponReady);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Focus);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_AutoRunning);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Controlled_BindInAir);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Invincible);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Immortal);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Physics_Collision_Disabled);

	
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_GameMenu);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
	ZODIAC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Escape);

	// Gameplay HUD Message channels
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_ReticleChanged);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_HealthChanged);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_AttributeValueChanged);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Message_WidgetChanged);

	// Gameplay Message channels
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Message_Elimination);
	
	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	ZODIAC_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	ZODIAC_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
	ZODIAC_API	extern const TMap<FGameplayTag, uint8> TagCustomMovementModeMap;
	
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_None);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Custom MovementMode
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Custom_None);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Custom_Running);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Custom_Walking);
	ZODIAC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Custom_Traversal);

};
